### ISSUE TITLE
Get_annotation_features style

### ISSUE THREAD

**Issue by kamilkrukowski** [kamilkrukowski/FinDocNLP#29]
We need the webelement -> pandas dataframe with features pipeline to have function definitions. 

We want to remove commented out legacy code, add comments for code blocks, add definitions to functions.
We need explanations of each column name generated by the functions.
We should convert some helper function names into private class syntax i.e.   (get_page_breaks -> _get_page_breaks)

Previously, some of the functions had legacy arguments -- For example an out_path argument that was completely unused and ignored.

**Comment by kamilkrukowski** [comment]
change indices to integer, not float

**Comment by yyitingli** [comment]
> change indices to integer, not float

**fix**

> We need the webelement -> pandas dataframe with features pipeline to have function definitions.
> 
> We want to remove commented out legacy code, add comments for code blocks, add definitions to functions. We need explanations of each column name generated by the functions. We should convert some helper function names into private class syntax i.e. (get_page_breaks -> _get_page_breaks)
> 
> Previously, some of the functions had legacy arguments -- For example an out_path argument that was completely unused and ignored.

    #-----------get attribute-------------------------------------------------#
    """
    value - the text value for the annotated label (e.g. 10-Q)
    found_index - index of the parent span webelement in the list of webelements
    annotation_index - index of the annotation in the list of annotation base on its webelemnt
    annotation_name - the name attribute from the annotation tag (e.g. us-gaap:SegmentReportingDisclosureTextBlock)
    annotation_id - the id attribute from the annotation tag (e.g. id3VybDovL2RvY3MudjEvZG9jOjY0OTlhYTNmZjJk...)
    annotation_format - the format attribute from the annotation tag (e.g. ixt:numdotdecimal)
    annotation_ix_type - the ix type attribute from the annotation tag (e.g. ix:nonfraction)
    annotation_unitref - the unit reference attribute from the annotation tag (e.g. usd)
    annotation_decimals - the decimal place attribute from the annotation tag (e.g. -3)
    annotation_contextref - the context reference attribute from the annotation tag (e.g. ic6b57dd3d48343d99e743248386420fc_I20201231)
    page_number - the page number for the label
    x - x coordinate
    y - y coordinate base on page number
    height - height of the tag
    width - width of the tag
    is_annotation - 1 if the value is annotation, 0 otherwise.
    """
