### ISSUE TITLE
Review style of file paths, change them to ```os.path.join``` and ```pathlib.Path```

### ISSUE THREAD

**Issue by kamilkrukowski** [kamilkrukowski/FinDocNLP#33]
Some file paths do not work between different file-systems i.e. Mac/Linux/Windows.

Please change paths to work on ALL systems by removing system specific paths and replacing them with the proper python calls to generate system-friendly paths.

**Comment by kamilkrukowski** [comment]
initially triage and check the setup directory files and the examples directory files to make sure they work -- afterwards pull request when necessary if someone else messes up file paths

**Comment by kamilkrukowski** [comment]
What is this? ```EDGAR/dataloader_neal.py```

Can we delete it from your branch? @NC-Zhao

**Comment by kamilkrukowski** [comment]
There have been path fixes available for over a week now that you haven't pulled so you're recoding stuff that other people have done already.

**Comment by NC-Zhao** [comment]
> What is this? `EDGAR/dataloader_neal.py`
> 
> Can we delete it from your branch? @NC-Zhao

That was the dataloader with the path fixed only to my PC. It should be deleted.

**Comment by NC-Zhao** [comment]
I assume that `sys.path.append('../')` does the same as `sys.path.append('..')`?
