### ISSUE TITLE
Finding Neighboring Webelements - Reconcile 'Div' and 'Pagebreak' webelement parsing schemes

### ISSUE THREAD

**Issue by yyitingli** [kamilkrukowski/FinDocNLP#34]
Two approaches:
1. split up the document by page breaker tag. Grouping all the text on the same page and using it as the neighboring text.
2. use the text in the parent div container for the label as the neighboring text

**Comment by yyitingli** [comment]
Solution:
1. use the parse_text_by_page(self)
2. still in process

**Comment by kamilkrukowski** [comment]
Run visual tests with red border bounding boxes on detected elements, present to team

**Comment by kamilkrukowski** [comment]
There is an option here:
We could just find all horizontal line breaks (hr) and their y position. Then, we can just subtract y positions to find page numbers of webelement. We can also find neighbors by looking at y distance, or xy euclidean distance.
