### ISSUE TITLE
```parser.find_page_location``` does not work on entire dataset

### ISSUE THREAD

**Issue by kamilkrukowski** [kamilkrukowski/FinDocNLP#38]
setup/generate_dataset.py

Traceback (most recent call last):                                                                                                                                                    
  File "/home/seresne/ml/capstone/FinDocNLP/setup/generate_dataset.py", line 33, in <module>
    features = parser.process_file(tikr, doc, fname) 
  File "/home/seresne/ml/capstone/FinDocNLP/setup/../EDGAR/parser.py", line 383, in process_file
    features = self.get_annotation_features(elems, annotation_dict)
  File "/home/seresne/ml/capstone/FinDocNLP/setup/../EDGAR/parser.py", line 328, in get_annotation_features
    page_location = self.find_page_location()
  File "/home/seresne/ml/capstone/FinDocNLP/setup/../EDGAR/parser.py", line 284, in find_page_location
    page_location = {page_number: [0,page_breaks[0].location["y"]]}
IndexError: list index out of range

**Comment by yyitingli** [comment]
Hi Kamil, 
> File "/home/seresne/ml/capstone/FinDocNLP/setup/../EDGAR/parser.py", line 284, in find_page_location
page_location = {page_number: [0,page_breaks[0].location["y"]]}
IndexError: list index out of range

I think the problem here is that page_breaks = self.driver.find_elements(By.TAG_NAME, 'hr') returns empty list in the find_page_location(self) function. It would be very helpful if you could send me the year of the 10-q html you are using or a file path to the file?

**Comment by kamilkrukowski** [comment]
filename: d105283d10q.htm
submission: 0001193125-19-212578
tikr: gs

**Comment by kamilkrukowski** [comment]
Is there a potential to push a quick patch that sets some fields to 'empty' in the dataframe? We can characterize coverage and percentage of missing fields later to determinate how important this is to triage.

**Comment by yyitingli** [comment]
> Is there a potential to push a quick patch that sets some fields to 'empty' in the dataframe? We can characterize coverage and percentage of missing fields later to determinate how important this is to triage.

I think we can set all the df.fillna("empty") or .replace() to change the value in df.

**Comment by kamilkrukowski** [comment]
This probably requires rewriting some get_annotation_features logic -- I think it is used in downstream calculations

**Comment by kamilkrukowski** [comment]
Here is some exception handling, but we may want to keep this issue and clean it up later

**Comment by yyitingli** [comment]
No longer needed!

**Comment by yyitingli** [comment]
We no longer need the find page location for the new parser.
