### ISSUE TITLE
Parser.py ```ix:numeric``` and ```ix:non-numeric``` convert try-except pattern into regex

### ISSUE THREAD

**Issue by kamilkrukowski** [kamilkrukowski/FinDocNLP#40]
The runtime and the style of using sequential try-except to detect the presence of a specific tag is problematic.

This should be near line 205 in parser.py

We should refactor with a regex on the webelement.text field in some manner.

(We need to expand the tag_list at some point and we can't scale this using the except pattern)

**Comment by kamilkrukowski** [comment]
@NC-Zhao , Since you've did basically the same thing for ParserFilter can you do this? Should be ~10 lines of code change

**Comment by NC-Zhao** [comment]
I think `elem.get_attribute("outerHTML")` will do the trick. I currently does not have my laptop with me thus cannot use Selenium to make sure my solution works. I will work on that during our meeting Tuesday.

**Comment by kamilkrukowski** [comment]
a regex filter on ```elem.text``` detecting the children, or iterating through a child list might both work. There's a lot of ways to do this -- Thanks for the heads up on soft-deadlines!

**Comment by kamilkrukowski** [comment]
@NC-Zhao This is a good first step before you try to improve the runtime on [54](https://github.com/kamilkrukowski/FinDocNLP/issues/54)
