### ISSUE TITLE
Sanity check for regex parser

### ISSUE THREAD

**Issue by NC-Zhao** [kamilkrukowski/FinDocNLP#64]
I cannot come up with a good way to sanity check the regex parser in which the return element will be in the form of paired integers that indicate the beginning and ending of html string.

**Comment by kamilkrukowski** [comment]
We should base everything off the selenium approach --

Ultimately the question is to change the body of several functions but the outputs must match exactly.
You can implement a deterministic bijective mapping between the regex strings and selenium webelement.text body fields of the selenium parser. This also lets you take regex strings, map them to selenium, and have the selenium 'draw_border' function offer visual checks -- You should also ensure each output selenium webelement has a partner with the regex parser output and that the regex parser does not add extraneous output missing from the selenium parser.

**Comment by kamilkrukowski** [comment]
@NC-Zhao Does that help? can we close the issue?

**Comment by NC-Zhao** [comment]
Here is two different way to code this new parser:
1. Build an element tree from html, and then do the exactly same thing as selenium. Recurs back to the root of the tree to check if it is in a table. 
2. Using regex to match tag strings to find element. To determine if it is in table, try find a '<table' tag in front of that element, if success, try find a close tag '</table'. 
Currently I am planning on using the second one, in that case I will not have the bijection because I do not have a element tree, and it will be a large work to construct such bijection between nodes in element tree and string slices.

**Comment by kamilkrukowski** [comment]
It looks to me like #2 will be a lot faster runtime-wise.

For the ```<table>``` tag you will almost always find one before the current tag --> you need to find a ```<table>``` before a ```<\table>``` tag and that is enough to ensure the current element is inside a table. (If there is a ```<table>``` without a matching ```<\table>``` on the other side, we have bigger issues than this regex parser.)


You don't need an element tree for a bijection. I am not suggesting matching the tree structure --> I am suggesting that you can hash each regex element text field into a hash table, hash the webelement.text fields into a hash table, and that hash table must have 1-1 correspondence or else something went wrong.

**Comment by kamilkrukowski** [comment]
@NC-Zhao if you don't \@ ping me, I am not notified and will not see your comments.

**Comment by NC-Zhao** [comment]
I totally agree that the second will be faster, and that is the one having trouble. 

> You don't need an element tree for a bijection. I am not suggesting matching the tree structure --> I am suggesting that you can hash each regex element text field into a hash table, hash the webelement.text fields into a hash table, and that hash table must have 1-1 correspondence or else something went wrong.

If there are repeated text, there will be no bijection. @kamilkrukowski

**Comment by kamilkrukowski** [comment]
Besides empty strings or “ “ space strings this shouldn’t be an issue. Annotated elements outside tables should have unique text fields.

there may be an annotation on a number in a table where that number is not unique — but for now we can just worry about bijections on non-table elements.
